#this two values the cluster end point and the kubeconfig are data
#generated by the kind-cluster during its creation and
#those data are shared daynamically to the root module

output "cluster_endpoint" {
  value       = kind_cluster.stock_cluster.endpoint
  description = "The endpoint for the Kubernetes API server"
}



output "kubeconfig" {
  value       = kind_cluster.stock_cluster.kubeconfig
  description = "Raw kubeconfig for the cluster."
  sensitive   = true
}
